/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KitchenUI;
import order.*;

/**
 *
 * @author Jallais
 */
public class MainKitchenUI extends javax.swing.JFrame {
    private OrderListManager orderListManager;
    private OrderListFrame orderListFrame;
    
    /**
     * Creates new form MainUI
     */
    public MainKitchenUI(OrderListManager orderListManager) {
        this.orderListManager = orderListManager;
        this.orderListFrame = new OrderListFrame(this.orderListManager, this);
        this.setTitle("Cuisine");
        initComponents();
        this.setSize(800, 600);
        this.showListOrderFrame();
    }
    
    private void showListOrderFrame() {
//        this.removeAll();
        this.add(this.orderListFrame);
        this.revalidate();
        this.repaint();
    }
    
    public void showOrderDetailFrame(Order order) {
        this.remove(this.orderListFrame);
        this.add(new OrderDetailPanel(order));
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
