/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package KitchenUI;
import javax.swing.JLabel;
import javax.swing.JPanel;
import order.*;
import product.*;

/**
 *
 * @author Jallais
 */
public class OrderDetailPanel extends javax.swing.JPanel {
    private Order order;
    
    /**
     * Creates new form OrderDetailPanel
     */
    public OrderDetailPanel(Order order) {
        this.order = order;
        initComponents();
        this.OrderNameLabel.setText(this.order.getName());
        this.setProducts();
    }
    
    private void setProducts() {
        for (Product p: this.order.getProducts()) {
            JPanel panel = new JPanel();
            panel.add(new JLabel(p.getDescription()));
            this.ProductsPanel.add(panel);
        }
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PricesPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ProductsPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        OrderNameLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Retour");
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jButton2.setText("Annuler");
        jPanel3.add(jButton2);

        jButton3.setText("Valider");
        jPanel3.add(jButton3);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prix (€)");
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);

        PricesPanel.setLayout(new javax.swing.BoxLayout(PricesPanel, javax.swing.BoxLayout.LINE_AXIS));
        jPanel5.add(PricesPanel, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Produit(s)");
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        ProductsPanel.setLayout(new javax.swing.BoxLayout(ProductsPanel, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(ProductsPanel, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        OrderNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderNameLabel.setText("jLabel1");
        jPanel7.add(OrderNameLabel);

        jPanel2.add(jPanel7, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OrderNameLabel;
    private javax.swing.JPanel PricesPanel;
    private javax.swing.JPanel ProductsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
