/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BorneUI;

import order.*;

/**
 *
 * @author Jallais
 */
public class MainBorneUI extends javax.swing.JFrame {
    private ChoiceFrame choiceFrame;
    private EditOrderFrame editOrderFrame;
    private OrderManager order;
    
    public MainBorneUI(OrderManager order, OrderListManager orderListManager) {
        this.setTitle("Borne de commande");
        this.order = order;
        this.choiceFrame = new ChoiceFrame(this);
        this.editOrderFrame = new EditOrderFrame(this.order, this, orderListManager);
        initComponents();
        this.setSize(800, 600);
        this.add(this.choiceFrame);
    }
    
    public void showEditOrderFrame(String type) {
        this.remove(this.choiceFrame);
        this.add(this.editOrderFrame);
        
        if (type.equals("menu")) {
            this.editOrderFrame.showSelectMenusFrame();
        } else {
            this.editOrderFrame.showSelectProductsFrame();
        }
        
        this.revalidate();
        this.repaint();
    }
    
    public void showChoiceFrame() {
        this.remove(this.editOrderFrame);
        this.add(this.choiceFrame);
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
